# String limits
USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 32

EMAIL_MIN_LENGTH = 3
EMAIL_MAX_LENGTH = 254

WORKOUT_NAME_MAX_LENGTH = 100
EXERCISE_NAME_MAX_LENGTH = 100
MUSCLE_GROUP_NAME_MAX_LENGTH = 50

NOTES_MAX_LENGTH = 500

# Numeric limits
REPS_MIN = 0
REPS_MAX = 1000

WEIGHT_MIN = 0
WEIGHT_MAX = 2000

REST_MIN = 0
REST_MAX = 3600